### ISSUE TITLE
Question about paper

### ISSUE THREAD

**Issue by JarveeLee** [SimonKohl/probabilistic_unet#1]
During training why do you sample latent space from Posterior Net instead of from prior net, to be the same as test procedure ?

**Comment by SimonKohl** [comment]
Hi there! During training you operate in reconstruction mode, i.e. you try to faithfully reconstruct a target image (here a segmentation) from a sample of the posterior. In VAEs this is necessary in order to learn the semantic structure of the latent space. At test time on the other hand, you sample from the prior, which in the case of conditional VAEs is a predicted distribution over this latent space and in the case of unconditional VAEs most of the times simply a normal distribution over the latent space. I hope this helps? I would recommend to further look into the original publications or this nice [tutorial](https://arxiv.org/abs/1606.05908).
